libtomcrypt: define LTC_MPI at the same time as LTC_DER
LTC_DER is always defined when LTC_NO_PKCS is NOT defined (which is our
case). Since LTC_DER depends on LTC_MPI let's set that one at the same
time. Fixes the following build error:

 $ make CFG_CRYPTO=n
 [...]
 core/lib/libtomcrypt/src/headers/tomcrypt_custom.h:629:5: error: #error ASN.1 DER requires MPI functionality
   629 |    #error ASN.1 DER requires MPI functionality
       |     ^~~~~

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>